# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 800, 600))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 800, 580))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(840, 10, 291, 641))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btnUpload = QtWidgets.QPushButton(self.frame_2)
        self.btnUpload.setGeometry(QtCore.QRect(10, 10, 281, 51))
        self.btnUpload.setObjectName("btnUpload")
        self.lblImgPath = QtWidgets.QLabel(self.frame_2)
        self.lblImgPath.setGeometry(QtCore.QRect(10, 90, 281, 21))
        self.lblImgPath.setObjectName("lblImgPath")
        self.btnOriginImg = QtWidgets.QPushButton(self.frame_2)
        self.btnOriginImg.setGeometry(QtCore.QRect(10, 220, 271, 41))
        self.btnOriginImg.setObjectName("btnOriginImg")
        self.btnDetect = QtWidgets.QPushButton(self.frame_2)
        self.btnDetect.setGeometry(QtCore.QRect(10, 280, 271, 41))
        self.btnDetect.setObjectName("btnDetect")
        self.listResult = QtWidgets.QListWidget(self.frame_2)
        self.listResult.setGeometry(QtCore.QRect(10, 370, 271, 192))
        self.listResult.setAcceptDrops(False)
        self.listResult.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listResult.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listResult.setViewMode(QtWidgets.QListView.ListMode)
        self.listResult.setObjectName("listResult")
        self.btnRemove = QtWidgets.QPushButton(self.frame_2)
        self.btnRemove.setGeometry(QtCore.QRect(10, 590, 271, 41))
        self.btnRemove.setObjectName("btnRemove")
        self.lblResult = QtWidgets.QLabel(self.frame_2)
        self.lblResult.setGeometry(QtCore.QRect(20, 340, 101, 21))
        self.lblResult.setObjectName("lblResult")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 590, 801, 61))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btnCreateMask = QtWidgets.QPushButton(self.frame_3)
        self.btnCreateMask.setGeometry(QtCore.QRect(620, 10, 171, 41))
        self.btnCreateMask.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnCreateMask.setObjectName("btnCreateMask")
        self.btnMove = QtWidgets.QPushButton(self.frame_3)
        self.btnMove.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.btnMove.setObjectName("btnMove")
        self.btnSelect = QtWidgets.QPushButton(self.frame_3)
        self.btnSelect.setGeometry(QtCore.QRect(60, 10, 41, 41))
        self.btnSelect.setObjectName("btnSelect")
        self.lblSize = QtWidgets.QLabel(self.frame_3)
        self.lblSize.setGeometry(QtCore.QRect(120, 10, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lblSize.setFont(font)
        self.lblSize.setObjectName("lblSize")
        self.btnZoomOut = QtWidgets.QPushButton(self.frame_3)
        self.btnZoomOut.setGeometry(QtCore.QRect(170, 10, 41, 41))
        self.btnZoomOut.setObjectName("btnZoomOut")
        self.btnZoomIn = QtWidgets.QPushButton(self.frame_3)
        self.btnZoomIn.setGeometry(QtCore.QRect(360, 10, 41, 41))
        self.btnZoomIn.setObjectName("btnZoomIn")
        self.sliderSize = QtWidgets.QSlider(self.frame_3)
        self.sliderSize.setGeometry(QtCore.QRect(220, 20, 131, 22))
        self.sliderSize.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSize.setObjectName("sliderSize")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnUpload.setText(_translate("MainWindow", "Upload"))
        self.lblImgPath.setText(_translate("MainWindow", "Filename: "))
        self.btnOriginImg.setText(_translate("MainWindow", "Origin"))
        self.btnDetect.setText(_translate("MainWindow", "Detect"))
        self.btnRemove.setText(_translate("MainWindow", "Remove"))
        self.lblResult.setText(_translate("MainWindow", "Detect Result"))
        self.btnCreateMask.setText(_translate("MainWindow", "Create Mask"))
        self.btnMove.setText(_translate("MainWindow", "M"))
        self.btnSelect.setText(_translate("MainWindow", "C"))
        self.lblSize.setText(_translate("MainWindow", "100%"))
        self.btnZoomOut.setText(_translate("MainWindow", "B"))
        self.btnZoomIn.setText(_translate("MainWindow", "S"))

